### ISSUE TITLE
Crashing with LUA 5.3 architecture.

### ISSUE THREAD

**Issue by Namelessys** [zenith391/OCCity#1]
The game is crashing on startup if you are using the LUA 5.3 architecture.

Stack traceback:
```
 /home/OCCity.lua:32: attempt to index a nil value (global 'bit32')
stack traceback:
	machine:805: in metamethod '__index'
	/home/OCCity.lua:32: in global 'utf8byte'
	/home/OCCity.lua:93: in field 'draw'
	/home/OCCity.lua:111: in field 'fill'
	/home/OCCity.lua:181: in local 'drawResidentialHouse'
	/home/OCCity.lua:219: in main chunk
```

Edit:
Is working fine if you are using LUA 5.2.

**Comment by zenith391** [comment]
Fixing that, the thing is that i fixed this error by importing `bit32` as `bit`, except i actually used `bit32` at some point in code.
